throttle_pid:
  ros__parameters:
    Kp: 12.299999999999999
    Ki: 0.136
    Kd: 38.4
pitch_pid:
  ros__parameters:
    Kp: 0.0
    Ki: 0.0
    Kd: 0.0
roll_pid:
  ros__parameters:
    Kp: 0.0
    Ki: 0.0
    Kd: 0.0
